using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BCCR.TipoDeCambio
{
    public static class Mapping
    {
        private static readonly Dictionary<int, string> data = new Dictionary<int, string>
    {
        { 3617, "Bancos Privados" },
        { 3151, "Banco BCT" },
        { 3152, "Banco Davivienda" },
        { 3153, "Banco Citibank Costa Rica" },
        { 3154, "Banco CMB" },
        { 3180, "Banco Cathay" },
        { 3181, "Banco Bac San José" },
        { 3182, "Banco Uno" },
        { 3183, "Banco Lafise" },
        { 3184, "Banco Improsa" },
        { 3185, "Banco Interfin" },
        { 3186, "Banco Promerica" },
        { 3187, "Scotiabank C.R." },
        { 3566, "Banco General Costa Rica S.A" },
        { 3619, "Bancos Públicos" },
        { 3146, "Banco Crédito Agrícola de Cartago" },
        { 3148, "Banco de Costa Rica" },
        { 3149, "Banco Nacional" },
        { 3179, "Banco Popular" },
        { 3631, "Casas de Cambio" },
        { 3201, "Casa Cambio Tele Dólar" },
        { 3203, "Casa Cambio Global Exchange" },
        { 3417, "Casa de cambio Interbolsa" },
        { 3556, "Casa Cambio Soluciones Monetarias S.A." },
        { 19860, "Casa de Cambio Latin American Exchange, S.A." },
        { 22964, "Serviexpreso Money Transfer Casa de Cambio" },
        { 3636, "Cooperativas" },
        { 3196, "Cooperativa Credecoop" },
        { 3197, "Cooperativa Coocique" },
        { 3198, "Cooperativa San Marcos" },
        { 3199, "Coopemex" },
        { 3200, "Coopenae" },
        { 3289, "Coopealianza" },
        { 3345, "Coopesanramon R.L." },
        { 3361, "Coopeorotina R.L." },
        { 3563, "Coopeservidores R.L." },
        { 3597, "Coope-Ande N° 1 R.L" },
        { 86037, "Coopemep R.L." },
        { 90285, "Coopecaja R.L." },
        { 3652, "Financieras" },
        { 3188, "Financiera Londres" },
        { 3189, "Financiera Comeca" },
        { 3190, "Financiera Multivalores" },
        { 3191, "Prival Bank (Costa Rica) S.A" },
        { 3192, "Financiera Miravalles" },
        { 3193, "Financiera Cafsa" },
        { 3341, "Financiera DESYFIN S.A." },
        { 3593, "Financiera MultiMoney S.A." },
        { 3691, "Mutuales" },
        { 3194, "Mutual Alajuela" },
        { 3195, "Mutual Cartago" },
        { 3734, "Puestos de Bolsa" },
        { 3204, "Puesto de Bolsa Aldesa Valores" },
        { 3281, "Interbolsa" },
        { 3337, "BN Valores Puesto Bolsa" },
        { 3427, "Acobo Puesto de Bolsa S.A." },
        { 3549, "INS Valores Puesto de Bolsa S.A." },
        { 3552, "BCT Valores Puesto de Bolsa S.A." },
        { 18922, "Mercado Valores de C.R. P.B." },
        { 19728, "Popular Valores Puesto de Bolsa, Compra" },
        { 22601, "BCR Valores Puesto de Bolsa, Compra" },
        { 22849, "Mutual Valores Puesto de Bolsa, Compra" },
        { 23701, "PB Inversiones SAMA" },
        { 3618, "Bancos Privados" },
        { 3210, "Banco BCT" },
        { 3211, "Banco Davivienda" },
        { 3213, "Banco CMB" },
        { 3214, "Banco Cathay" },
        { 3215, "Banco Bac San José" },
        { 3217, "Banco Lafise" },
        { 3218, "Banco Improsa" },
        { 3220, "Banco Promerica" },
        { 3221, "Scotiabank C.R." },
        { 3568, "Banco General Costa Rica S.A" },
        { 3620, "Bancos Públicos" },
        { 3207, "Banco de Costa Rica" },
        { 3208, "Banco Nacional" },
        { 3209, "Banco Popular" },
        { 3632, "Casas de Cambio" },
        { 3271, "Casa Cambio Tele Dólar" },
        { 3277, "Casa Cambio Global Exchange" },
        { 3637, "Cooperativas" },
        { 3230, "Cooperativa Credecoop" },
        { 3231, "Cooperativa Coocique" },
        { 3232, "Cooperativa San Marcos" },
        { 3234, "Coopenae" },
        { 3290, "Coopealianza" },
        { 3567, "Coopeservidores R.L." },
        { 3598, "Coope-Ande N° 1 R.L" },
        { 86038, "Coopemep R.L." },
        { 90286, "Coopecaja R.L." },
        { 3653, "Financieras" },
        { 3223, "Financiera Comeca" },
        { 3225, "Prival Bank S.A" },
        { 3227, "Financiera Cafsa" },
        { 3342, "Financiera DESYFIN S.A." },
        { 3594, "Financiera MultiMoney S.A." },
        { 3692, "Mutuales" },
        { 3228, "Mutual Alajuela" },
        { 3229, "Mutual Cartago" },
        { 3735, "Puestos de Bolsa" },
        { 3338, "BN Valores Puesto Bolsa" },
        { 3553, "BCT Valores Puesto de Bolsa S.A." },
        { 18923, "Mercado Valores de C.R. P.B." },
        { 19729, "Popular Valores Puesto de Bolsa" },
        { 23702, "PB Inversiones SAMA" }
    };

        public static string? GetName(int id)
        {
            return data.TryGetValue(id, out var name) ? name : null;
        }
    }
}
